config/routes.rb
# coding: utf-8
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root  'home#index'

  get   'home/index'
  get   'sheet'                => 'home#sheet',       :as => :sheet
  get   'ranking'              => 'home#ranking',     :as => :ranking
  get   'closed'               => 'home#closed',      :as => :closed

  get   'lottery'              => 'lottery#top',      :as => :lottery
  get   'lottery/ready/:lp_id' => 'lottery#ready',    :as => :ready_lottery
  post  'lottery/cast'         => 'lottery#cast',     :as => :cast_lottery
  get   'lottery/win'          => 'lottery#win',      :as => :win_lottery
  get   'lottery/lose'         => 'lottery#lose',     :as => :lose_lottery
  get   'lottery/not_yet'      => 'lottery#not_yet',  :as => :not_yet_lottery

  get   'enquete'              => 'enquete#new',      :as => :new_enquete
  patch 'enquete/:id'          => 'enquete#answer',   :as => :answer_enquete
  get   'enquete/thanks'       => 'enquete#thanks',   :as => :thanks_enquete

  get   'condition/:token'     => 'condition#show',   :as => :condition
  get   'coupon/:token'        => 'coupon#show',      :as => :coupon
  get   'coupon/:token/used'   => 'coupon#used',      :as => :coupon_used

  get   'contact'              => 'contact#new',      :as => :new_contact
  post  'contact/confirm'      => 'contact#confirm',  :as => :confirm_contact
  post  'contact/complete'     => 'contact#complete', :as => :complete_contact

  devise_for :users, controllers: {
               confirmations:      'users/confirmations',
               passwords:          'users/passwords',
               registrations:      'users/registrations',
               sessions:           'users/sessions',
               unlocks:            'users/unlocks',
               omniauth_callbacks: 'users/omniauth_callbacks'
             }


  devise_scope :user do
    get 'users/password/instructions' => 'users/passwords#instructions',      :as => :instructions_user_password
    get 'users/password/reset'        => 'users/passwords#reset',             :as => :reset_user_password
    get 'users/after_sign_up'         => 'users/registrations#after_sign_up', :as => :after_sign_up_registration
  end

  namespace :api do
    get  'ping'                  => 'ping#index'
    post 'sheet/check_condition'
    post 'sheet/update_name'
    post 'sheet/share_twitter'
    post 'stamp/push'
    post 'coupon/use'
    post 'lottery/share_twitter'
  end

  get '*anywhere'                => 'errors#routing_error'
end

app/views/shared/_footer.html.slim
footer.global__footer
  p.footer__link--to-top
    a.js-trigger__smooth-scroll(href="#section__top") ▲
  .footer__copyright
    p.copyright__text--copyright
      |
        &copy; 赤塚不二夫／おそ松さん製作委員会
        &copy; Copyright TOKYU CORPORATION All Rights Reserved.
    p.copyright__text--powered
      = link_to 'powered by rev-stamp.com', 'http://rev-stamp.com'
    ul.copyright__links
      li.copyright__link--osomatsusan
        = link_to '', "http://osomatsusan.com/", :target => '_blank'
      li.copyright__link--tokyudentetsu
        = link_to '', "http://www.tokyu.co.jp/", :target => '_blank'

app/views/shared/_header.html.slim
header.global__header
  p.header__link--to-top
    = link_to 'TOP', root_path
  p.header__button--menu.js-trigger__toggle-header-menu.js-trigger__play-audio(data-audio-selector=".audio__menu")

app/views/shared/_header_menu.html.slim
.global__header-menu-overlay.js-element__header-menu-overlay
.global__header-menu.js-element__header-menu
  = link_to 'TOP', root_path
  p.js-trigger__open-notifications-modal お知らせ
  p.js-trigger__open-faq-modal よくある質問
  - if current_user and current_user.provider == 'email' and current_user.answered_enquete == true
    = link_to 'パスワード再設定', new_user_password_path
  /- = link_to 'お問い合わせ', new_contact_path
  p.js-trigger__open-terms-modal 利用規約
  - if current_user
    = link_to "ログアウト", destroy_user_session_path, :method => :delete

app/views/shared/_lottery_information.html.slim
p.information__heading ごあんない
ul.information__schedules
  li.information__schedule--1st
    p.schedule--1st__heading 1stステージ抽選日
    p.schedule--1st__duration 8月30日(火) 〜 9月12日(月)
  li.information__schedule--2nd
    p.schedule--2nd__heading 2ndステージ抽選日
    p.schedule--2nd__duration 9月24日(土) 〜 9月30日(金)
ul.information__details
  li.information__detail--how-to
    p.detail--how-to__heading 抽選方法
    ul.detail--how-to__procedures
      li.detail--how-to__procedure 欲しい賞を選択します
      li.detail--how-to__procedure その場で抽選が行われ、結果がでます
    ul.detail--how-to__notifications
      li.detail--how-to__notification スタンプラリーで獲得した抽選券の数だけ抽選ができます。
      li.detail--how-to__notification 1stステージで獲得した抽選券は、使用しなければ2ndステージに引き継ぐことができます。
  li.information__detail--prize
    p.detail--prize__heading 景品一覧
    ul.detail--prize__stages
      li.detail--prize__stage--1st
        p.stage--1st__heading 1stステージ
        ul.stage--1st__prize-list
          li.stage--1st__prize-item A賞 おそ急さん限定ぬいぐるみ 15名
          li.stage--1st__prize-item B賞 おそ急さん限定ポスターセット 30名
          li.stage--1st__prize-item C賞 おそ急さん限定シール 200名
      li.detail--prize__stage--2nd
        p.stage--2nd__heading 2ndステージ
        ul.stage--2nd__prize-list
          li.stage--2nd__prize-item A賞 おそ急さん限定抱きまくら 15名
          li.stage--2nd__prize-item
            | B賞 
            span.stage--2nd__prize-item--small おそ急さん限定アクリルキーホルダーセット
            |  30名
          li.stage--2nd__prize-item C賞 おそ急さん限定シール 200名
    p.detail--prize__notification 景品は変更になる場合があります。

app/views/shared/_modal_faq.html.slim
- faqs = [\
  {\
    title: "1stステージに入手した抽選券は2ndステージで使えますか？",\
    content: "使えます。"\
  },\
  {\
    title: "１つのスマートフォンで複数のシリアルコードは登録できますか？",\
    content: "スタンプラリーとツイッターをログアウトしていただければ、別アカウントで登録可能です。メール登録の方はスタンプラリーのログアウトをした後、別のメールアドレスで登録してください。"\
  },\
  {\
    title: "2ndに参加するには、セカンドのワンデーを買う必要がありますか？",\
    content: "一度登録されたシリアルナンバーで、2ndもご参加いただけます。ただし、2ndもスタンプを集めるには、ご購入をお勧めします。"\
  },\
  {\
    title: "３個目のスタンプでもらえる記念ノベルティ「トド松入場券」の引換期間はいつまでですか？",\
    content: "ファーストステージでゲットしたトド松入場券クーポンは、ファーストステージの間でしか引換できませんのでご注意ください。同様にセカンドステージでゲットしたトド松入場券のクーポンは、セカンドの開催期間に引換ください。"\
  },\
  {\
    title: "３個目のスタンプでもらえる記念ノベルティは何回でももらえるの？",\
    content: "1stで1枚、2ndで1枚しか引換できません。"\
  },\
  {\
    title: "アプリを入手する必要はありますか？",\
    content: "ありません。"\
  },\
  {\
    title: "おそ急は遅いんですか速いんですか？",\
    content: "渋谷から横浜まで26分でいけるんで、速い方かと！"\
  },\
  {\
    title: "おそ急ワンデーオープンチケットがもう1枚欲しい",\
    content: "お一人さま１回の購入につき、3枚まです。スタンプラリーは２周目もできる仕様になっておりますので、ぜひご利用ください。"\
  },\
  {\
    title: "特別入場券は、どこで交換できますか？",\
    content: "引換場所：二子玉川ライズ S.C.（タウンフロント１階）東急カードカウンターです。"\
  },\
  {\
    title: "シリアルナンバーを無くしてしまいました",\
    content: "一度登録されたシリアルナンバーはお手元に残しておく必要はございません。登録前に紛失された場合は、残念ながら再度お求め下さる必要がございます。"\
  },\
  {\
    title: "スタンプがうまく押せません",\
    content: "ポイントは3つあります。①スマートフォンを手に持って押しましょう。②押したときに画面上で滑らないようにしましょう。③画面からはみ出ないように注意しましょう。あとはぐっと軽く押し込むようにスタンプすればきちんとスタンプを押すことができます。その他不具合等が見られる場合は、お問い合わせ窓口からお問い合わせください。"\
  },\
  {\
    title: "スタンプしたときに音が出ません",\
    content: "通信状況、端末設定、端末の種類などの条件により音が出ない場合があります。音が出ない場合でもスタンプはたまっていきます。\n※お客さまの端末の速度制限等の場合に音が出ないことがあります。"\
  },\
  {\
    title: "スタンプラリーに参加するのに費用は必要ですか？",\
    content: "期間限定おそ急ワンデーオープンチケットを購入していただく必要があります。購入の際に受け取ったシリアルコードを登録してログインしてください。通信料並びに電車賃等についてはお客様のご負担となります。"\
  },\
  {\
    title: "スタンプラリーの開催地を教えてください",\
    content: "SHIBUYA109（８階エスカレーター横）、武蔵小杉東急スクエア（３階「靴下屋」前）、東急百貨店たまプラーザ店（１階センターコート）、東急プラザ蒲田（６階「Taka-Q」前）、東急ストア三軒茶屋店（サービスカウンター）、レミィ五反田（５階エスカレーター（上り）付近）、二子玉川ライズ S.C.（タウンフロント１階）です。"\
  },\
  {\
    title: "チョロ急は電車なんですか？",\
    content: "電車です。"\
  },\
  {\
    title: "デジタルスタンプを持って帰ったら押し放題ですか？",\
    content: "デジタルスタンプはそれぞれサーバーで管理していますので、持って帰って押すことはできません・・・。また、それは犯罪なので絶対にやめましょう。"\
  },\
  {\
    title: "パスワードを忘れた場合の対処方法を教えてください",\
    content: "ログイン画面の「パスワードを忘れた方はこちら」よりパスワード再設定を行うことができます。"\
  },\
  {\
    title: "フィーチャーフォン（ガラケー）でも遊べますか？",\
    content: "対応しておりません。"\
  },\
  {\
    title: "扱えないブラウザはありますか？",\
    content: "・Firefoxは認証できません。\n・safari プライベートモードでは認証できません。\n・一部のAndroid Browserの中には対応できないものがあります"\
  },\
  {\
    title: "一度スタンプを集め終わった後でも楽しめますか？",\
    content: "同じアカウントで何回でも繰り返しスタンプラリーに参加できます。たまったスタンプはスタンプコレクションに保存されますので何度でもお楽しみください。"\
  },\
  {\
    title: "仮登録メールが届かないのですが、どうしたらよいですか？",\
    content: "「ドメイン指定受信/拒否」を設定/解除していない、もしくはURL付きメールをブロックしている可能性が考えられます。\n「@rev-stamp.com」のドメインから送られてくるメールを許可していない場合は、携帯電話の設定を変更してください。 変更後、ログイン画面の「確認メールを再送したい方はこちら」からメールアドレスを入力して送信すると再度仮登録メールが送られますので、そちらから本登録を完了させてください。\n機種によっては、URLが記載されているメールを一律ブロックする設定になっているものもあります。 ドメイン指定とは別に、こちらも許可してから再度確認メールの再送をお願いいたします。"\
  },\
  {\
    title: "開催期間を教えてください",\
    content: "8月1日から9月25日まで開催します。ファーストステージが8月1日から8月28日まで、8月29日のメンテナンス日を挟んで、8月30日から9月25日までがセカンドステージとなります。26日から30日までは抽選会のみのご利用が可能です。"\
  },\
  {\
    title: "機種変更や端末を紛失した場合のスタンプ等はどうなりますか？",\
    content: "新しい機種でサイトにアクセスし、登録メールアドレスにてログインしていただければ、そのままご利用いただけます。"\
  },\
  {\
    title: "終了後はどうなりますか？",\
    content: "9月30日までは閲覧可能です。"\
  },\
  {\
    title: "推し急によって何か変わることはありますか？",\
    content: "何かが変わります！"\
  },\
  {\
    title: "対応端末を教えてください",\
    content: "Android、iOSのスマートフォンでご利用いただけます。\n但し、OSのバージョンなど推奨環境は下記になります。\n■Android\n・OSバージョン：Android 4.2.0以上\n・対応ブラウザ：Chrome\n※ Androidブラウザはほとんどの場合使用可能ですが、端末によっては使えない場合があります\n■iOS\n・OSバージョン：iOS 8.x以上\n・対応ブラウザ：Safari、Chrome\n※ safari プライベートモードでは認証できません。"\
  },\
  {\
    title: "退会の仕方を教えてください",\
    content: "最終日が過ぎますと自動的に退会します。"\
  },\
  {\
    title: "端末が通信していなくとも利用できますか？",\
    content: "ご利用できません。必ず端末が通信可能な状態でご利用ください。"\
  },\
  {\
    title: "抽選はいつできますか？",\
    content: "1stステージ抽選会は、8月30日～9月5日まで 2ndステージ抽選会は、9月24日～9月30日までです。スタンプラリー開催期間中も、当該期間は抽選が可能です。"\
  },\
  {\
    title: "同じスタンプを2回押すことはできますか？",\
    content: "同じ日に2回押すことはできませんが、翌日以降再び押すことができます。"\
  },\
  {\
    title: "保有しているスタンプや特典を譲渡することはできますか？",\
    content: "譲渡することはできません。スタンプや特典は取得時の会員様のみ利用することができます。"\
  },\
  {\
    title: "遊び方がわかりません",\
    content: "おそ急さん公式サイトの「遊び方」をご確認いただくか、それでも分からない場合は窓口へご連絡ください。"\
  }\
]

.global__modal--faq.js-element__modal-faq
  p.modal--faq__title
  p.modal--faq__button--close.js-trigger__close-faq-modal
  .modal--faq__list
    - faqs.each do |faq|
      .modal--faq__item.js-element__faq-item
        .faq-item__label.js-trigger__toggle-faq-accordion
          p.faq-label__title = shorten_modal_faq_title_label faq[:title]
        .faq-item__wrapper.js-element__faq-accordion
          .faq-item__inner
            p.faq-wrapper__title = faq[:title]
            p.faq-wrapper__content = hbr faq[:content]
            p.faq-wrapper__trigger--close.js-trigger__close-faq-accordion 閉じる

app/views/shared/_modal_notifications.html.slim
.global__modal--notifications.js-element__modal-notifications
  p.modal--notifications__title
  p.modal--notifications__button--close.js-trigger__close-notifications-modal
  .modal--notifications__list
    - @notifications.each do |notification|
      .modal--notifications__item.js-element__notifications-item
        .notifications-item__label.js-trigger__toggle-notifications-accordion
          p.notifications-label__date = notification.published_at.to_s(:date)
          p.notifications-label__title = shorten_modal_notification_title_label notification.title
        .notifications-item__wrapper.js-element__notifications-accordion
          .notifications-item__inner
            p.notifications-wrapper__date = notification.published_at.to_s(:date)
            p.notifications-wrapper__title = notification.title
            p.notifications-wrapper__content = hbr raw notification.content
            p.notifications-wrapper__trigger--close.js-trigger__close-notifications-accordion 閉じる

app/views/shared/_stamp_data.html.slim
script[src="https://pub.12cm.jp/sdk/echoss-esp2-light-min.js"]
- if Rails.env.development?
  span.js-data__stamp-api-key(data-api-key="#{ENV['STAMP_JAVASCRIPT_API_KEY_PRODUCTION']}")
- else
  span.js-data__stamp-api-key(data-api-key="#{ENV['STAMP_JAVASCRIPT_API_KEY_PRODUCTION']}")

app/views/shared/_tracking_script.html.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  
  ga('create', 'UA-80634639-1', 'auto');
  ga('send', 'pageview');