config/routes.rb
# coding: utf-8
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root  'home#index'

  get   'home/index'
  get   'sheet'                => 'home#sheet',       :as => :sheet
  get   'ranking'              => 'home#ranking',     :as => :ranking
  get   'closed'               => 'home#closed',      :as => :closed

  get   'lottery'              => 'lottery#top',      :as => :lottery
  get   'lottery/ready/:lp_id' => 'lottery#ready',    :as => :ready_lottery
  post  'lottery/cast'         => 'lottery#cast',     :as => :cast_lottery
  get   'lottery/win'          => 'lottery#win',      :as => :win_lottery
  get   'lottery/lose'         => 'lottery#lose',     :as => :lose_lottery
  get   'lottery/not_yet'      => 'lottery#not_yet',  :as => :not_yet_lottery

  get   'enquete'              => 'enquete#new',      :as => :new_enquete
  patch 'enquete/:id'          => 'enquete#answer',   :as => :answer_enquete
  get   'enquete/thanks'       => 'enquete#thanks',   :as => :thanks_enquete

  get   'condition/:token'     => 'condition#show',   :as => :condition
  get   'coupon/:token'        => 'coupon#show',      :as => :coupon
  get   'coupon/:token/used'   => 'coupon#used',      :as => :coupon_used

  get   'contact'              => 'contact#new',      :as => :new_contact
  post  'contact/confirm'      => 'contact#confirm',  :as => :confirm_contact
  post  'contact/complete'     => 'contact#complete', :as => :complete_contact

  devise_for :users, controllers: {
               confirmations:      'users/confirmations',
               passwords:          'users/passwords',
               registrations:      'users/registrations',
               sessions:           'users/sessions',
               unlocks:            'users/unlocks',
               omniauth_callbacks: 'users/omniauth_callbacks'
             }


  devise_scope :user do
    get 'users/password/instructions' => 'users/passwords#instructions',      :as => :instructions_user_password
    get 'users/password/reset'        => 'users/passwords#reset',             :as => :reset_user_password
    get 'users/after_sign_up'         => 'users/registrations#after_sign_up', :as => :after_sign_up_registration
  end

  namespace :api do
    get  'ping'                  => 'ping#index'
    post 'sheet/check_condition'
    post 'sheet/update_name'
    post 'sheet/share_twitter'
    post 'stamp/push'
    post 'coupon/use'
    post 'lottery/share_twitter'
  end

  get '*anywhere'                => 'errors#routing_error'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :login_required,           :except => [ :closed ]
  before_action :enquete_required,         :except => [ :closed ]
  before_action :set_current_sheet,        :only   => [ :index ]
  before_action :set_completed_sheet,      :only   => [ :sheet ]
  before_action :set_coupons,              :only   => [ :index ]
  before_action :set_unread_notifications, :only   => [ :index ]
  before_action :set_access_time,          :only   => [ :index ]

  def index
  end

  def sheet
  end

  def ranking
    @ranking = TopRanking.season.order(:rank).limit(Settings.top_ranking.display_rank_length)
    @ranking_users = User.find(@ranking.map {|r| r.user_id}).map{ |u| [u.id, { name: u.name, theme: u.theme }] }.to_h

    my_ranking = SelfRanking.season.where(:owner => current_user.id).first
    @my_ranking_users = my_ranking.arround_me if my_ranking
  end

  def lottery
  end

  def closed
    sign_out current_user if signed_in?
  end

  private
  def set_current_sheet
    @current_sheet = current_user.sheets.current_phase.includes(:stamps).current
    @current_sheet = current_user.create_new_sheet if @current_sheet.blank?
  end

  def set_completed_sheet
    @completed_sheets = current_user.sheets.completed
  end

  def set_coupons
    @coupons = []
    Coupon.current_phase.ordered.each do |coupon|
      user_coupon = current_user.user_coupons.where(:coupon_id => coupon.id).first

      if user_coupon.present?
        count = user_coupon.number
        image_path = coupon.list_image_path
      else
        count = 0
        image_path = coupon.list_blank_image_path
      end

      @coupons.push(
        {
          :count      => count,
          :path       => Rails.application.routes.url_helpers.coupon_path(coupon.token),
          :image_path => image_path,
          :present    => user_coupon.present?
        }
      )
    end
  end

  def set_unread_notifications
    if current_user.last_accessed_at.nil?
      @unread_notifications = @notifications
    else
      @unread_notifications = @notifications.where('published_at > ?', current_user.last_accessed_at)
    end
  end

  def set_access_time
    current_user.update_attributes! :last_accessed_at => Time.now
  end
end

app/helpers/home_helper.rb
# coding: utf-8
module HomeHelper
  def birthyear_collection
    (1950..2010).to_a.map do |year|
      if year == 1950
        ["#{year}年以前",year]
      elsif year == 2010
        ["#{year}年以降",year]
      else
        ["#{year}年",year]
      end
    end
  end

  def gender_collection
    User.genders.keys.map { |gender| [t("activerecord.enum.user.gender.#{gender}"), gender] }
  end

  def theme_collection
    User.themes.keys.map { |theme| [t("activerecord.enum.user.theme.#{theme}"), theme] }
  end

  def job_collection
    User.jobs.keys.map { |job| [t("activerecord.enum.user.job.#{job}"), job] }
  end

  def frequency_of_use_tokyu_collection
    User.frequency_of_use_tokyus.keys.map { |fout| [t("activerecord.enum.user.frequency_of_use_tokyu.#{fout}"), fout] }
  end

  def season_top_ranking_duration
    season_start = Time.parse Settings.top_ranking.season_start.to_s
    season_end   = Time.parse Settings.top_ranking.season_end.to_s

    "#{Settings.top_ranking.season_name}(#{season_start.to_s(:season_ranking)}~#{season_end.to_s(:season_ranking)})"
  end

  def season_self_ranking_duration
    season_start = Time.parse Settings.self_ranking.season_start.to_s
    season_end   = Time.parse Settings.self_ranking.season_end.to_s

    "#{Settings.self_ranking.season_name}(#{season_start.to_s(:season_ranking)}~#{season_end.to_s(:season_ranking)})"
  end

  def weekday time
    %w(日 月 火 水 木 金 土)[time.wday]
  end
end

app/views/home/closed.html.slim
p.home-closed__description 「おそ松さんスタンプラリー2016夏」は終了いたしました。たくさんのご参加ありがとうございました！

app/views/home/index.html.slim
- set_meta_tags({\
  description: '2016年夏開催、おそ急さんスランプラリー！東急沿線に散りばめられたスタンプを集めて限定おそ急さん商品をGET！',\
  keyword: 'おそ急スタンプラリー,おそ急さん,おそ急,東急スタンプラリー,東急電鉄,東急,おそスタ,おそ松さん,おそ松,カラ急,チョロ急,一急,十四急,トド急'\
})

h2.home-index__title
ul.home-index__current-stamps
  - (1..6).to_a.each do |i|
    li.home-index__current-stamp.js-element__stamp-wrapper(data-index="#{i}")
      - if @current_sheet.sheet_stamps.where(:position => i).first.present?
        = image_tag "#{Settings.stamp.image_dir}/#{@current_sheet.phase}/#{@current_sheet.sheet_stamps.where(:position => i).first.stamp.image_filename}.#{Settings.stamp.image_extension}", class: 'js-element__stamp-image', 'data-position': i

- if Rails.env.local?
  /- test code
  p.js-trigger__push-stamp(data-stamp-id="A1534965" data-api-url="#{api_stamp_push_path}") おそ松
  p.js-trigger__push-stamp(data-stamp-id="A1533852" data-api-url="#{api_stamp_push_path}") カラ松
  p.js-trigger__push-stamp(data-stamp-id="A1532847" data-api-url="#{api_stamp_push_path}") チョロ松
  p.js-trigger__push-stamp(data-stamp-id="A1533777" data-api-url="#{api_stamp_push_path}") 一松
  p.js-trigger__push-stamp(data-stamp-id="A1533910" data-api-url="#{api_stamp_push_path}") 十四松
  p.js-trigger__push-stamp(data-stamp-id="A1533948" data-api-url="#{api_stamp_push_path}") トド松
  p.js-trigger__push-stamp(data-stamp-id="A1531653" data-api-url="#{api_stamp_push_path}") イヤミ
  css:
    .js-trigger__push-stamp {
      display: inline-block;
      padding: 10px;
      cursor: pointer;
      border: 2px solid #000;
      margin: 10px 50px;
    }
  /- test code

p.home-index__text--description
  |
    おそ急さんスタンプラリー２０１６夏は
    9月25日(日)にて終了いたしました。
p.home-index__text--comment
  |
    抽選会は9月30日(金)まで実施中だよ！
ul.home-index__links
  li.home-index__link--how-to-play
    a(href="http://www.tokyu.co.jp/osokyusan/coupon.html" target="_blank")
      | 遊び方
  li.home-index__link--map
    a.js-trigger__play-audio(href="http://www.tokyu.co.jp/osokyusan/index.html" data-audio-selector=".audio__link--map" target="_blank")
      | MAP
  li.home-index__link--stamp-collection
    a.js-trigger__play-audio(href="#{sheet_path}" data-audio-selector=".audio__link--sheet")
      |
        スタンプ
        コレクション
  li.home-index__link--lottery
    a.js-trigger__play-audio(href="#{lottery_path}" data-audio-selector=".audio__link--lottery")
      |
        スタンプラリー
        抽選会場
  li.home-index__link--ranking
    a.js-trigger__play-audio(href="#{ranking_path}" data-audio-selector=".audio__link--ranking")
      |
        スタンプ
        ランキング
.home-index__coupons
  h3.coupons__title GETしたクーポン
  ul.coupons__list
    - @coupons.each do |coupon|
      li.coupons__item
        p.coupons-item__image
          - if coupon[:present] && coupon[:count] > 0
            = link_to image_tag(coupon[:image_path]), coupon[:path]
          - else
            = image_tag coupon[:image_path]
        p.coupons-item__count #{coupon[:count]}枚

- if @current_sheet.number == 1
  span.js-data__audio-dir(data-audio-dir="#{Settings.stamp.audio_dir}/first/")
- else
  span.js-data__audio-dir(data-audio-dir="#{Settings.stamp.audio_dir}/common/")
- ['lottery', 'map', 'ranking', 'sheet'].each do |name|
  audio(src="/static/application/audio/home/index/link/#{name}.mp3" class="audio__link--#{name}")

- unless Rails.env.local?
  = render partial: 'shared/stamp_data'

- if @unread_notifications.present?
  .global__popup--unread-notifications.state__display.js-element__popup--unread-notifications
    .popup--unread-notifications__wrapper
      p.popup--unread-notifications__title お知らせ
      .popup--unread-notifications__content
        - @unread_notifications.each do |notification|
          .unerad-notifications__item
            p.notifications-item__title = notification.title
            p.notifications-item__date = notification.published_at.to_s(:date)
            p.notifications-item__content = hbr raw notification.content
      p.popup--unread-notifications__button--close.js-trigger__close-popup-unread-notifications とじる

= javascript_include_tag 'libs/howler.min'

app/views/home/ranking.html.slim
- set_meta_tags({\
  title: 'スタンプランキング',\
  description: 'おそ急さんスタンプラリーのランキングをチェック！ ライバルよりさらにライジングしよう！',\
  keyword: 'おそ急スタンプラリー,おそ急さん,おそ急,東急スタンプラリー,東急電鉄,東急,おそスタ,おそ松さん,おそ松'\
})

h2.home-ranking__title
- if @ranking.count < Settings.top_ranking.display_rank_length and @my_ranking_users.blank?
  p.home-ranking__no-data ランキングは未集計となります。ランキングは1日に1回更新されるので、また明日アクセスしてみてくださいね。
- else
  ul.home-ranking__ranking-list
    - unless @ranking.count < Settings.top_ranking.display_rank_length
      li.home-ranking__ranking-item.type__season
        .ranking__outer
          p.ranking__duration = season_top_ranking_duration
          .ranking__inner
            .ranking__labels
              p.ranking__label--rank 順位
              p.ranking__label--name なまえ
              p.ranking__label--count スタンプ数
            - @ranking.each do |ranking|
              .ranking__user(theme="#{@ranking_users[ranking.user_id][:theme]}")
                p.ranking__rank(rank="#{ranking.rank}") = "#{ranking.rank}位"
                p.ranking__name = @ranking_users[ranking.user_id][:name]
                p.ranking__count = ranking.stamp_count
    - if @my_ranking_users.present?
      li.home-ranking__ranking-item.type__my-season
        .ranking__outer
          p.ranking__duration = season_self_ranking_duration
          .ranking__inner
            .ranking__labels
              p.ranking__label--rank 順位
              p.ranking__label--name なまえ
              p.ranking__label--count スタンプ数
            - @my_ranking_users.each do |ranking_user|
              .ranking__user(theme="#{ranking_user[:theme]}")
                p.ranking__rank(rank="#{ranking_user[:rank]}") = "#{ranking_user[:rank]}位"
                p.ranking__name = ranking_user[:name]
                p.ranking__count = ranking_user[:stamp_count]

app/views/home/sheet.html.slim
- set_meta_tags({\
  title: 'スタンプコレクション',\
  description: '今まで集めたスタンプを確認できます。',\
  keyword: 'おそ急スタンプラリー,おそ急さん,おそ急,東急スタンプラリー,東急電鉄,東急,おそスタ,おそ松さん,おそ松,コレクション,スタンプラリー,スタンプコレクション'\
})

h2.home-sheet__title
.home-sheet__order
  .order__input--select
    select.js-trigger__select-sheet-order
      option(value="completed-at_desc" selected) 新しい順
      option(value="completed-at_asc") 古い順
      option(value="name_asc") 名前順
      option(value="name_desc") 名前逆順
  p.order__button--submit.js-trigger__change-sheet-order 並び替え
ul.home-sheet__collection.js-element__sheet-list
  - if @completed_sheets.present?
    - @completed_sheets.each do |completed_sheet|
      li.collection__item.js-element__sheet-item(data-name="#{completed_sheet.name}" data-completed-at="#{completed_sheet.completed_at}")
        .collection-item__input--name
          = form_tag api_sheet_update_name_path, :method => :post, :remote => true, class: 'js-element__form--sheet-name' do
            = hidden_field :sheet, :token, :value => completed_sheet.token
            = text_field :sheet, :name, :value => completed_sheet.name, class: 'js-element__input--sheet-name'
        ul.collection-item__stamp-list
          - completed_sheet.sheet_stamps.each do |sheet_stamp|
            li.collection-item__stamp-item
              = image_tag "#{Settings.stamp.image_dir}/#{completed_sheet.phase}/#{sheet_stamp.stamp.image_filename}.#{Settings.stamp.image_extension}"
        .collection-item__information
          p.information__completed-at カード取得日：#{completed_sheet.completed_at.to_s(:completed_at)}
          ul.information__share-buttons
            - if current_user.twitter_access_token
              li.information__share-button--twitter.js-trigger__open-tweet-popup(data-sheet-token="#{completed_sheet.token}")
            - else
              li.information__share-button--twitter
                = link_to '', omniauth_authorize_path('user', 'twitter', :referrer_path => request.fullpath)
            li.information__share-button--facebook
              = link_to '', "https://www.facebook.com/dialog/feed?app_id=#{Settings.facebook.app_id}&link=#{root_url}&redirect_uri=#{sheet_url}&title=#{URI.encode 'おそ急さんスタンプラリー2016年夏'}&description=#{URI.encode '2016年夏開催、おそ急さんスランプラリー！東急沿線に散りばめられたスタンプを集めて限定おそ急さん商品をGET！'}&picture=#{completed_sheet.share_image_url}"
            /- li.information__share-button--line
  - else
    p.collection__text--not-found シートはまだありません
.home-sheet__popup--tweet.js-element__tweet-popup
  .popup-tweet__wrapper
    = form_tag api_sheet_share_twitter_path, :method => :post, :remote => true, class: 'js-element__tweet-form' do
      = hidden_field :sheet, :token, class: 'js-element__sheet-token'
      = hidden_field :user, :token, :value => current_user.token
      p.popup-tweet__label Twitterにシェアする
      p.popup-tweet__button--close.js-trigger__close-tweet-popup
      = text_area :tweet, :content, class: 'popup-tweet__input js-element__tweet-input', 'data-default-text': " #おそ急さんスタンプラリー 開催中！ シートが完成したよ☆ みんなはどんなシートができた？ #おそ急さん"
      .popup-tweet__actions
        p.popup-tweet__tweet-button.js-element__tweet-button シェアする
        p.popup-tweet__text-counter.js-element__tweet-text-count