config/routes.rb
# coding: utf-8
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root  'home#index'

  get   'home/index'
  get   'sheet'                => 'home#sheet',       :as => :sheet
  get   'ranking'              => 'home#ranking',     :as => :ranking
  get   'closed'               => 'home#closed',      :as => :closed

  get   'lottery'              => 'lottery#top',      :as => :lottery
  get   'lottery/ready/:lp_id' => 'lottery#ready',    :as => :ready_lottery
  post  'lottery/cast'         => 'lottery#cast',     :as => :cast_lottery
  get   'lottery/win'          => 'lottery#win',      :as => :win_lottery
  get   'lottery/lose'         => 'lottery#lose',     :as => :lose_lottery
  get   'lottery/not_yet'      => 'lottery#not_yet',  :as => :not_yet_lottery

  get   'enquete'              => 'enquete#new',      :as => :new_enquete
  patch 'enquete/:id'          => 'enquete#answer',   :as => :answer_enquete
  get   'enquete/thanks'       => 'enquete#thanks',   :as => :thanks_enquete

  get   'condition/:token'     => 'condition#show',   :as => :condition
  get   'coupon/:token'        => 'coupon#show',      :as => :coupon
  get   'coupon/:token/used'   => 'coupon#used',      :as => :coupon_used

  get   'contact'              => 'contact#new',      :as => :new_contact
  post  'contact/confirm'      => 'contact#confirm',  :as => :confirm_contact
  post  'contact/complete'     => 'contact#complete', :as => :complete_contact

  devise_for :users, controllers: {
               confirmations:      'users/confirmations',
               passwords:          'users/passwords',
               registrations:      'users/registrations',
               sessions:           'users/sessions',
               unlocks:            'users/unlocks',
               omniauth_callbacks: 'users/omniauth_callbacks'
             }


  devise_scope :user do
    get 'users/password/instructions' => 'users/passwords#instructions',      :as => :instructions_user_password
    get 'users/password/reset'        => 'users/passwords#reset',             :as => :reset_user_password
    get 'users/after_sign_up'         => 'users/registrations#after_sign_up', :as => :after_sign_up_registration
  end

  namespace :api do
    get  'ping'                  => 'ping#index'
    post 'sheet/check_condition'
    post 'sheet/update_name'
    post 'sheet/share_twitter'
    post 'stamp/push'
    post 'coupon/use'
    post 'lottery/share_twitter'
  end

  get '*anywhere'                => 'errors#routing_error'
end

app/models/contact.rb
# coding: utf-8
class Contact
  include ActiveModel::Model

  attr_accessor :name, :name_kana, :email, :message

  validates_presence_of :name, message: 'お名前を入力してください'
  validates_presence_of :name_kana, message: 'お名前(カナ)を入力してください'
  validates_presence_of :email, message: 'メールアドレスを入力してください'
  validates_presence_of :message, message: 'お問い合わせ内容を入力してください'
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new contact_params

    render :new and return unless @contact.valid?
  end

  def complete
    @contact = Contact.new contact_params

    render :new and return if params[:back]

    ContactMailer.create_new(@contact).deliver
    ContactMailer.received(@contact).deliver
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :name_kana, :email, :message)
  end
end

app/views/contact/complete.html.slim
.contact-complete__title--main
.contact-complete__title--sub 送信完了しました

app/views/contact/confirm.html.slim
.contact-confirm__title--main
.contact-confirm__title--sub 入力確認
= form_for @contact, :url => complete_contact_path do |f|
  .contact-confirm__table
    = f.hidden_field :name
    p.contact-confirm__label--name お名前
    p.contact-confirm__value--name = @contact.name
    = f.hidden_field :name_kana
    p.contact-confirm__label--name-kana
      |
        お名前
        (カナ)
    p.contact-confirm__value--name-kana = @contact.name_kana
    = f.hidden_field :email
    p.contact-confirm__label--email
      |
        メール
        アドレス
    p.contact-confirm__value--email = @contact.email
    = f.hidden_field :message
    p.contact-confirm__label--message お問い合わせ内容
    p.contact-confirm__value--message = @contact.message
  = f.submit '再編集する', name: 'back', class: 'contact-confirm__link--back'
  = f.submit '送信', class: 'contact-confirm__button--submit'

app/views/contact/new.html.slim
.contact-new__title,
= form_for @contact, :url => confirm_contact_path do |f|
  p.contact-new__label--name お名前
  - if @contact.errors[:name].count > 0
    - @contact.errors[:name].each do |error|
      p.contact-new__error #{error}
  = f.text_field :name, class: 'contact-new__input--name'
  p.contact-new__label--name-kana お名前(カナ)
  - if @contact.errors[:name_kana].count > 0
    - @contact.errors[:name_kana].each do |error|
      p.contact-new__error #{error}
  = f.text_field :name_kana, class: 'contact-new__input--name-kana'
  p.contact-new__label--email メールアドレス
  - if @contact.errors[:email].count > 0
    - @contact.errors[:email].each do |error|
      p.contact-new__error #{error}
  = f.email_field :email, class: 'contact-new__input--email'
  p.contact-new__label--message お問い合わせ内容
  - if @contact.errors[:message].count > 0
    - @contact.errors[:message].each do |error|
      p.contact-new__error #{error}
  = f.text_area :message, class: 'contact-new__input--message'
  = f.submit '確認' , class: 'contact-new__button--submit'