config/routes.rb
# coding: utf-8
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root  'home#index'

  get   'home/index'
  get   'sheet'                => 'home#sheet',       :as => :sheet
  get   'ranking'              => 'home#ranking',     :as => :ranking
  get   'closed'               => 'home#closed',      :as => :closed

  get   'lottery'              => 'lottery#top',      :as => :lottery
  get   'lottery/ready/:lp_id' => 'lottery#ready',    :as => :ready_lottery
  post  'lottery/cast'         => 'lottery#cast',     :as => :cast_lottery
  get   'lottery/win'          => 'lottery#win',      :as => :win_lottery
  get   'lottery/lose'         => 'lottery#lose',     :as => :lose_lottery
  get   'lottery/not_yet'      => 'lottery#not_yet',  :as => :not_yet_lottery

  get   'enquete'              => 'enquete#new',      :as => :new_enquete
  patch 'enquete/:id'          => 'enquete#answer',   :as => :answer_enquete
  get   'enquete/thanks'       => 'enquete#thanks',   :as => :thanks_enquete

  get   'condition/:token'     => 'condition#show',   :as => :condition
  get   'coupon/:token'        => 'coupon#show',      :as => :coupon
  get   'coupon/:token/used'   => 'coupon#used',      :as => :coupon_used

  get   'contact'              => 'contact#new',      :as => :new_contact
  post  'contact/confirm'      => 'contact#confirm',  :as => :confirm_contact
  post  'contact/complete'     => 'contact#complete', :as => :complete_contact

  devise_for :users, controllers: {
               confirmations:      'users/confirmations',
               passwords:          'users/passwords',
               registrations:      'users/registrations',
               sessions:           'users/sessions',
               unlocks:            'users/unlocks',
               omniauth_callbacks: 'users/omniauth_callbacks'
             }


  devise_scope :user do
    get 'users/password/instructions' => 'users/passwords#instructions',      :as => :instructions_user_password
    get 'users/password/reset'        => 'users/passwords#reset',             :as => :reset_user_password
    get 'users/after_sign_up'         => 'users/registrations#after_sign_up', :as => :after_sign_up_registration
  end

  namespace :api do
    get  'ping'                  => 'ping#index'
    post 'sheet/check_condition'
    post 'sheet/update_name'
    post 'sheet/share_twitter'
    post 'stamp/push'
    post 'coupon/use'
    post 'lottery/share_twitter'
  end

  get '*anywhere'                => 'errors#routing_error'
end

app/controllers/api/lottery_controller.rb
class Api::LotteryController < Api::ApplicationController
  before_action :set_twitter_client

  def share_twitter
    lottery_prize = LotteryPrize.where(:id => params[:lottery_prize][:id]).first
    error 404 if lottery_prize.blank?

    tweet_text = params[:tweet][:content]
    error 422 if tweet_text.blank?

    @twitter_client.update_with_media(
      "#{tweet_text} #{Settings.site.url}",
      open(lottery_prize.win_image_url)
    )

    success
  end
end

app/controllers/lottery_controller.rb
class LotteryController < ApplicationController
  before_action :login_required
  before_action :enquete_required
  before_action :redirect_not_opened, :except => [ :not_yet ]
  before_action :set_lottery_prizes, :only => [ :top ]
  before_action :set_present_ticket, :only => [ :top, :ready, :cast ]
  before_action :redirect_top_if_no_ticket, :only => [ :ready, :cast ]
  before_action :set_lottery_prize, :only => [ :ready, :cast, :win, :lose ]
  before_action :set_lottery_unique_serial, :only => [ :win ]

  def top
  end

  def ready
  end

  def cast
    # rest_prize_count = @lottery_unique_serials.count
    # all_user_ticket_count = @present_coupon.user_coupons.sum :number

    # cast = rand(all_user_ticket_count)
    # cast = rand(20)
    # result = cast <= rest_prize_count
    cast = rand 10000
    result = cast <= (@lottery_prize.rate * 10000)
    # @present_ticket.decrement! :number, 1

    if result
      # lus = @lottery_unique_serials.first.code_for_params
      # @lottery_unique_serials.first.update_attributes!(
      #   :is_already_used => true,
      #   :user_id         => current_user.id
      # )
      redirect_to win_lottery_path(:lus => "this,code_is,dummy", :lp_id => @lottery_prize.id)
    else
      redirect_to lose_lottery_path(:lp_id => @lottery_prize.id)
    end
  end

  def win
  end

  def lose
  end

  def not_yet
    redirect_to lottery_path if Settings.lottery.is_open
  end

  private
  def redirect_not_opened
    redirect_to not_yet_lottery_path unless Settings.lottery.is_open
  end

  def set_lottery_prizes
    @lottery_prizes = LotteryPrize.stage(Settings.lottery.current_stage).ordered
  end

  def set_present_ticket
    @present_coupon = Coupon.present_ticket.first
    redirect_to root_path if @present_coupon.blank?

    @present_ticket = current_user.user_coupons.where(:coupon_id => @present_coupon.id).first
  end

  def redirect_top_if_no_ticket
    # redirect_to lottery_path if @present_ticket.blank? or @present_ticket.number == 0
  end

  def set_lottery_prize
    case action_name
    when 'ready', 'win', 'lose'
      lp_id = params[:lp_id]
    when 'cast'
      lp_id = params[:lottery][:lp_id]
    end

    redirect_to lottery_path and return if lp_id.blank?

    @lottery_prize = LotteryPrize.where(:id => lp_id).first
    redirect_to lottery_path and return if @lottery_prize.blank?

    @lottery_unique_serials = @lottery_prize.lottery_unique_serials.not_used
  end

  def set_lottery_unique_serial
    lus_params = params[:lus].split(',')
    # redirect_to lottery_path and return if lus_params.length != 3

    # @lottery_unique_serial = LotteryUniqueSerial.used.where(
    #   :lottery_id   => lus_params[0],
    #   :lottery_pass => lus_params[1],
    #   :lottery_code => lus_params[2]
    # ).first

    # redirect_to lottery_path and return if @lottery_unique_serial.blank?
    # redirect_to lottery_path and return if current_user.lottery_unique_serials.exclude? @lottery_unique_serial
    # redirect_to lottery_path and return unless @lottery_prize.lottery_unique_serials.include? @lottery_unique_serial

    @lus          = params[:lus]
    @lottery_id   = lus_params[0]
    @lottery_pass = lus_params[1]
    @lottery_code = lus_params[2]
  end
end

app/helpers/lottery_helper.rb
module LotteryHelper
  def mailer_href lottery_id, lottery_pass, lottery_code, win_url, user_name, user_serial_code
    subject = Settings.lottery.unique_serial_mail.subject.clone
    body = Settings.lottery.unique_serial_mail.body.clone

    body.gsub! /\{\{user_name\}\}/, user_name
    body.gsub! /\{\{user_serial_code\}\}/, user_serial_code
    body.gsub! /\{\{lottery_id\}\}/, lottery_id
    body.gsub! /\{\{lottery_pass\}\}/, lottery_pass
    body.gsub! /\{\{lottery_code\}\}/, lottery_code
    body.gsub! /\{\{win_url\}\}/, win_url

    "mailto:?subject=#{CGI.escape subject}&body=#{CGI.escape body}"
  end
end

app/views/lottery/lose.html.slim
h2.lottery-lose__title
p.lottery-lose__grade = "#{@lottery_prize.grade}賞"
p.lottery-lose__name = nobr @lottery_prize.name
p.lottery-lose__label
p.lottery-lose__image
  = image_tag "#{Settings.lottery.result_image_dir}/lose.jpg"
p.lottery-lose__button--retry
  = link_to 'もう1度回す', lottery_path
p.lottery-lose__button--to-top
  = link_to 'TOPに戻る', root_path

app/views/lottery/not_yet.html.slim
- set_meta_tags({\
  title: 'スタンプラリー抽選のお知らせ',\
  description: 'おそ急さんスタンプラリーに関して、抽選のお知らせです。',\
  keyword: 'おそ急スタンプラリー,おそ急さん,おそ急,グッズ,レアグッズ,東急スタンプラリー,東急電鉄,東急,おそスタ,おそ松さん,おそ松'\
})

h2.lottery-not_yet__title
p.lottery-not_yet__description 現在、抽選会場はお休みです。
.lottery-not_yet__information
  = render partial: 'shared/lottery_information'

app/views/lottery/ready.html.slim
h2.lottery-ready__title
p.lottery-ready__grade = "#{@lottery_prize.grade}賞"
p.lottery-ready__name = nobr @lottery_prize.name
.lottery-ready__animation
  = image_tag 'lottery/ready/lottery__ready__picture--lottery-machine.png', :class => 'js-element__animation-lottery-machine'
= form_tag cast_lottery_path, :method => :post, :remote => false, :class => 'js-element__form--cast-lottery' do
  = hidden_field :lottery, :lp_id, :value => @lottery_prize.id
  p.lottery-ready__button--to-result.js-trigger__cast-lottery 結果を見る

app/views/lottery/top.html.slim
- set_meta_tags({\
  title: 'スタンプラリー抽選に挑戦',\
  description: '集めたスタンプで限定商品が当たる抽選にチャレンジしよう！ここでしかゲットできないレアなおそ急さんが手に入るビックチャンス！',\
  keyword: 'おそ急スタンプラリー,おそ急さん,おそ松グッズ,グッズ,レアグッズ,おそ急,東急スタンプラリー,東急電鉄,東急,おそスタ,おそ松さん,おそ松'\
})

h2.lottery-top__title
p.lottery-top__description ほしい賞をタップしてね
ul.lottery-top__prize-list
  - @lottery_prizes.each do |lottery_prize|
    li(class="lottery-top__prize-item--#{lottery_prize.grade.downcase}")
      = link_to ready_lottery_path(:lp_id => lottery_prize.id) do
        p.prize-item__grade = "#{lottery_prize.grade}賞"
        p.prize-item__name = hbr lottery_prize.name
        p.prize-item__count = "残り#{lottery_prize.lottery_unique_serials.not_used.count}個"
p.lottery-top__notification
  | ※賞品の残数が０個の場合でもシステムの仕様上、抽選にはご参加可能となっております。
  br
  | 各賞品の残り個数を必ずご確認の上、抽選にご参加下さい。
p.lottery-top__rest-chance
  | あと
  br
  span.lottery-top__rest-count = @present_ticket.present? ? @present_ticket.number : 0
  | 回まわせるよ
.lottery-top__information
  = render partial: 'shared/lottery_information'

app/views/lottery/win.html.slim
h2.lottery-win__title
p.lottery-win__grade = "#{@lottery_prize.grade}賞"
p.lottery-win__name = nobr @lottery_prize.name
p.lottery-win__label
p.lottery-win__image
  = image_tag @lottery_prize.win_image_path
- if current_user.twitter_access_token
  p.lottery-win__button--tweet.js-trigger__open-tweet-popup Twitterにシェアする
- else
  p.lottery-win__button--tweet
    = link_to 'Twitterにシェアする', omniauth_authorize_path('user', 'twitter', :referrer_path => request.fullpath)
.lottery-win__serial-codes
  p.serial-codes__id = "ID：#{@lottery_id}"
  p.serial-codes__pass = "パス：#{@lottery_pass}"
  p.serial-codes__code = "当選番号：#{@lottery_code}"
p.lottery-win__note--save-code
  |
    必ず上記の当選情報は
    いずれかの方法で保管してください。
ul.lottery-win__list--how-to-save-code
  li.lottery-win__item--how-to-save-code
    | 画面を撮影(スクショ)して保存する
  li.lottery-win__item--how-to-save-code
    | メモなどにコピー＆ペーストしておく
  li.lottery-win__item--how-to-save-code
    |
      紙などにメモを取る(大文字小文字にご注意ください)
p.lottery-win__note--apply 当選情報を保存したら、応募フォームから応募しよう！
p.lottery-win__button--apply-form
  = link_to '応募フォームはこちら', 'https://qooker.jp/Q/auto/ja/osokyustamp/hassou/', :target => '_blank'
.lottery-win__popup--tweet.js-element__tweet-popup
  .popup-tweet__wrapper
    = form_tag api_lottery_share_twitter_path, :method => :post, :remote => true, class: 'js-element__tweet-form' do
      = hidden_field :lottery_prize, :id, :value => @lottery_prize.id
      p.popup-tweet__label Twitterにシェアする
      p.popup-tweet__button--close.js-trigger__close-tweet-popup
      = text_area :tweet, :content, class: 'popup-tweet__input js-element__tweet-input', 'data-default-text': " #おそ急さんスタンプラリー で「#{@lottery_prize.name_long}」が当たった！ 家宝にスッペ～！ #おそ急さん"
      .popup-tweet__actions
        p.popup-tweet__tweet-button.js-element__tweet-button シェアする
        p.popup-tweet__text-counter.js-element__tweet-text-count